"""event_table

Revision ID: bee71ff82f66
Revises: 94f6b4d83de1
Create Date: 2019-12-01 16:53:30.495915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee71ff82f66'
down_revision = '94f6b4d83de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('img_url', sa.String(length=256), nullable=True),
    sa.Column('event_url', sa.String(length=256), nullable=True),
    sa.Column('date', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_address'), 'event', ['address'], unique=False)
    op.create_index(op.f('ix_event_category'), 'event', ['category'], unique=False)
    op.create_index(op.f('ix_event_date'), 'event', ['date'], unique=False)
    op.create_index(op.f('ix_event_description'), 'event', ['description'], unique=False)
    op.create_index(op.f('ix_event_event_url'), 'event', ['event_url'], unique=False)
    op.create_index(op.f('ix_event_img_url'), 'event', ['img_url'], unique=False)
    op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=False)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_img_url'), table_name='event')
    op.drop_index(op.f('ix_event_event_url'), table_name='event')
    op.drop_index(op.f('ix_event_description'), table_name='event')
    op.drop_index(op.f('ix_event_date'), table_name='event')
    op.drop_index(op.f('ix_event_category'), table_name='event')
    op.drop_index(op.f('ix_event_address'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
